{
  "id": "EUVD-2018-11713",
  "enisaUuid": "dc174eec-ca65-35d2-bcb8-08ef359bec84",
  "description": "python before versions 2.7.15, 3.4.9, 3.5.6rc1, 3.6.5rc1 and 3.7.0 is vulnerable to catastrophic backtracking in pop3lib's apop() method. An attacker could use this flaw to cause denial of service.",
  "datePublished": "Jun 18, 2018, 2:00:00 PM",
  "dateUpdated": "Aug 5, 2024, 3:44:12 AM",
  "baseScore": 4.3,
  "baseScoreVersion": "3.0",
  "baseScoreVector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
  "references": [
    "https://www.suse.com/security/cve/CVE-2018-1060.html",
    "https://www.debian.org/security/2018/dsa-4307",
    "https://www.debian.org/security/2018/dsa-4306",
    "https://access.redhat.com/errata/RHSA-2020:1346",
    "https://access.redhat.com/errata/RHSA-2020:1268",
    "https://access.redhat.com/errata/RHSA-2019:3725",
    "https://access.redhat.com/errata/RHSA-2019:1260",
    "https://access.redhat.com/errata/RHSA-2018:3041",
    "https://ubuntu.com/security/CVE-2018-1060",
    "https://advisories.mageia.org/CVE-2018-1060.html",
    "https://alas.aws.amazon.com/cve/html/CVE-2018-1060.html",
    "https://linux.oracle.com/cve/CVE-2018-1060.html",
    "http://www.securitytracker.com/id/1042001",
    "https://lists.debian.org/debian-lts-announce/2018/09/msg00031.html",
    "https://bugs.python.org/issue32981",
    "https://usn.ubuntu.com/3817-2/",
    "https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-release-candidate-1",
    "https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-6-release-candidate-1",
    "https://access.redhat.com/errata/RHSA-2018:3505",
    "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1060",
    "https://usn.ubuntu.com/3817-1/",
    "https://lists.debian.org/debian-lts-announce/2018/09/msg00030.html",
    "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JSKPGPZQNTAULHW4UH63KGOOUIDE4RRB/",
    "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/AEZ5IQT7OF7Q2NCGIVABOWYGKO7YU3NJ/",
    "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/46PVWY5LFP4BRPG3BVQ5QEEFYBVEXHCK/",
    "https://access.redhat.com/errata/RHBA-2019:0327",
    "https://support.hpe.com/hpsc/doc/public/display?docLocale=en_US&docId=emr_na-hpesbst03951en_us",
    "https://www.oracle.com/security-alerts/cpujan2020.html",
    "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html"
  ],
  "aliases": [
    "CVE-2018-1060",
    "GSD-2018-1060"
  ],
  "assigner": "redhat",
  "epss": 0.96,
  "enisaIdProduct": [
    {
      "id": "4641aa9c-2cb2-3775-bf77-03f159be87ea",
      "product": {
        "name": "Python"
      },
      "product_version": "python 3.7.0"
    },
    {
      "id": "95a92a34-f03c-3d3e-a392-891f34a2638d",
      "product": {
        "name": "Python"
      },
      "product_version": "python 2.7.15"
    },
    {
      "id": "b3021e45-5fad-3334-bd77-c9e806910577",
      "product": {
        "name": "Python"
      },
      "product_version": "python 3.5.6"
    },
    {
      "id": "fd2ed3f7-8083-3981-85ae-65a88b959472",
      "product": {
        "name": "Python"
      },
      "product_version": "python 3.4.9"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "51421763-f065-3478-9ac7-57bdcc2d045c",
      "vendor": {
        "name": "[UNKNOWN]"
      }
    }
  ],
  "cve": "CVE-2018-1060"
}