{
  "id": "EUVD-2018-0080",
  "enisaUuid": "1b6e564d-c8e9-320a-8b0e-6c9e7a2d1337",
  "description": "An issue was discovered in Project Jupyter JupyterHub OAuthenticator 0.6.x before 0.6.2 and 0.7.x before 0.7.3. When using JupyterHub with GitLab group whitelisting for access control, group membership was not checked correctly, allowing members not in the whitelisted groups to create accounts on the Hub. (Users were not allowed to access other users' accounts, but could create their own accounts on the Hub linked to their GitLab account. GitLab authentication not using gitlab_group_whitelist is unaffected. No other Authenticators are affected.)",
  "datePublished": "Feb 18, 2018, 3:29:00 AM",
  "dateUpdated": "Aug 25, 2021, 4:30:14 AM",
  "baseScore": 8.8,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
  "references": [
    "https://blog.jupyter.org/security-fix-for-jupyterhub-gitlab-oauthenticator-7b14571d1f76",
    "https://github.com/jupyterhub/oauthenticator/commit/1845c0e4b1bff3462c91c3108c85205acd3c75a2",
    "https://github.com/jupyterhub/oauthenticator/blob/8499dc2/CHANGELOG.md#073---2018-02-16",
    "https://github.com/jupyterhub/oauthenticator/blob/8499dc2/CHANGELOG.md#073---2018-02-16",
    "https://github.com/advisories/GHSA-8x3m-m3x9-54fj",
    "https://nvd.nist.gov/vuln/detail/CVE-2018-7206",
    "https://github.com/pypa/advisory-database/tree/main/vulns/jupyterhub/PYSEC-2018-151.yaml",
    "https://github.com/pypa/advisory-database/tree/main/vulns/oauthenticator/PYSEC-2018-68.yaml"
  ],
  "aliases": [
    "CVE-2018-7206",
    "PYSEC-2018-151",
    "GHSA-8x3m-m3x9-54fj"
  ],
  "assigner": "mitre",
  "epss": 0.65,
  "enisaIdProduct": [
    {
      "id": "59d7924c-3db3-3076-b5ad-37d5ce182d52",
      "product": {
        "name": "n/a"
      },
      "product_version": "n/a"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "303c279a-1f96-3e02-b5b6-99f09c3044e4",
      "vendor": {
        "name": "n/a"
      }
    }
  ],
  "cve": "CVE-2018-7206"
}