{
  "id": "EUVD-2022-24619",
  "enisaUuid": "8bd4dd82-7a2c-3efd-bd9c-dcde3ebf36f0",
  "description": "A denial of service vulnerability was found in tildearrow Furnace. It has been classified as problematic. This is due to an incomplete fix of CVE-2022-1211. It is possible to initiate the attack remotely but it requires user interaction. The issue got fixed with the patch 0eb02422d5161767e9983bdaa5c429762d3477ce.",
  "datePublished": "Apr 10, 2022, 3:15:15 PM",
  "dateUpdated": "Apr 15, 2025, 2:41:32 PM",
  "baseScore": 4.3,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
  "references": [
    "https://github.com/tildearrow/furnace/issues/325#issuecomment-1094139655",
    "https://github.com/tildearrow/furnace/commit/0eb02422d5161767e9983bdaa5c429762d3477ce",
    "https://vuldb.com/?id.196755"
  ],
  "aliases": [
    "CVE-2022-1289",
    "GSD-2022-1289"
  ],
  "assigner": "VulDB",
  "epss": 0.31,
  "enisaIdProduct": [
    {
      "id": "57b66db9-57f4-3b90-b785-f3209f86dd09",
      "product": {
        "name": "Furnace"
      },
      "product_version": "n/a"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "dc6fe055-e5dd-3472-ae28-b356cf41260c",
      "vendor": {
        "name": "tildearrow"
      }
    }
  ]
}