{
  "id": "EUVD-2021-0387",
  "enisaUuid": "a4cfab3f-07d5-3809-8834-f725fcbac1e9",
  "description": "TensorFlow is an end-to-end open source platform for machine learning. In affected versions an attacker can cause a denial of service in `boosted_trees_create_quantile_stream_resource` by using negative arguments. The [implementation](https://github.com/tensorflow/tensorflow/blob/84d053187cb80d975ef2b9684d4b61981bca0c41/tensorflow/core/kernels/boosted_trees/quantile_ops.cc#L96) does not validate that `num_streams` only contains non-negative numbers. In turn, [this results in using this value to allocate memory](https://github.com/tensorflow/tensorflow/blob/84d053187cb80d975ef2b9684d4b61981bca0c41/tensorflow/core/kernels/boosted_trees/quantiles/quantile_stream_resource.h#L31-L40). However, `reserve` receives an unsigned integer so there is an implicit conversion from a negative value to a large positive unsigned. This results in a crash from the standard library. We have patched the issue in GitHub commit 8a84f7a2b5a2b27ecf88d25bad9ac777cd2f7992. The fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range.",
  "datePublished": "Aug 12, 2021, 9:15:00 PM",
  "dateUpdated": "Aug 27, 2021, 3:22:45 AM",
  "baseScore": 5.5,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
  "references": [
    "https://github.com/tensorflow/tensorflow/commit/8a84f7a2b5a2b27ecf88d25bad9ac777cd2f7992",
    "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-gf88-j2mg-cc82",
    "https://nvd.nist.gov/vuln/detail/CVE-2021-37661",
    "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-574.yaml",
    "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-772.yaml",
    "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-283.yaml",
    "https://www.suse.com/security/cve/CVE-2021-37661.html",
    "https://security.archlinux.org/CVE-2021-37661"
  ],
  "aliases": [
    "CVE-2021-37661",
    "GHSA-gf88-j2mg-cc82",
    "PYSEC-2021-574"
  ],
  "assigner": "GitHub_M",
  "epss": 0.01,
  "enisaIdProduct": [
    {
      "id": "a1f23bdd-228a-3e90-8968-61797148af4b",
      "product": {
        "name": "tensorflow"
      },
      "product_version": "2.5.0, < 2.5.1"
    },
    {
      "id": "c79ce6f0-bdd5-35f5-a2c0-ba9c3113b970",
      "product": {
        "name": "tensorflow"
      },
      "product_version": "2.4.0, < 2.4.3"
    },
    {
      "id": "fa71a497-3535-30bf-8a7c-253f31341ca6",
      "product": {
        "name": "tensorflow"
      },
      "product_version": "< 2.3.4"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "8e1f4568-09e7-3207-a992-2ec6c049eacc",
      "vendor": {
        "name": "tensorflow"
      }
    }
  ],
  "cve": "CVE-2021-37661"
}