{
  "id": "EUVD-2022-0207",
  "enisaUuid": "cebd114f-5126-3c24-b60c-aaa66da9da9c",
  "description": "ReDoS in py library when used with subversion ",
  "datePublished": "Oct 16, 2022, 12:00:23 PM",
  "dateUpdated": "May 14, 2025, 7:24:41 PM",
  "baseScore": 5.3,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AC:L/AV:N/A:L/C:N/I:N/PR:N/S:U/UI:N",
  "references": [
    "https://github.com/advisories/GHSA-w596-4wvx-j9j6",
    "https://nvd.nist.gov/vuln/detail/CVE-2022-42969",
    "https://github.com/pytest-dev/py/issues/287",
    "https://github.com/pytest-dev/py/issues/288",
    "https://github.com/pytest-dev/pytest/issues/10392",
    "https://github.com/pypa/advisory-database/tree/main/vulns/py/PYSEC-2022-42969.yaml",
    "https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316",
    "https://news.ycombinator.com/item?id=34163710",
    "https://pypi.org/project/py",
    "https://www.suse.com/security/cve/CVE-2022-42969.html"
  ],
  "aliases": [
    "CVE-2022-42969",
    "GHSA-w596-4wvx-j9j6",
    "PYSEC-2022-42969"
  ],
  "assigner": "mitre",
  "epss": 0.1,
  "enisaIdProduct": [
    {
      "id": "718d4682-c89f-3cd6-856e-3ff0f7728657",
      "product": {
        "name": "n/a"
      },
      "product_version": "n/a"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "0aa58f7a-a6f8-39bb-a21a-1b871043c18f",
      "vendor": {
        "name": "n/a"
      }
    }
  ]
}